site_name: Scrite User Guide
site_url: https://www.scrite.io/docs/userguide
theme:
  name: material
  logo: images/scrite-appicon.png
  palette: 
    - scheme: default
      primary: purple
      accent: purple
extra_css:
  - styles/style.css
markdown_extensions:
  - toc:
      permalink: true
      separator: '-'
      toc_depth: 4
plugins:
  - mkdocs-video
hooks:
  - hooks.py
nav:
  - index.md
  - quickstart.md
  - user-interface.md
  - screenplay.md
  - files.md
  - languages.md
  - scriptalay.md
  - imports.md
  - exports.md
  - structure.md
  - templates.md
  - notebook.md
  - reports.md
  - support.md